version: '3.7'

services:
    traefik:
        init: true
        image: "traefik:v2.4"
        ports:
            - "80:80"
            - "8080:8080"
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    api:
        init: true
        build:
            context: ./
            dockerfile: ./configurations/api/Dockerfile
        restart: always
        expose:
            - "80"
        command: gunicorn munity.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:80 --workers=${GUNICORN_WORKER_NUMBER} --timeout 90 --reload --log-level ${API_LOG_LEVEL} --access-logfile=- --error-logfile=-
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=HostRegexp(`${API_SUFFIX_URL}`, `{workspace:[a-z]+}.${API_SUFFIX_URL}`)"
        volumes:
            - ./api:/usr/src/app
            - ./plugins:/usr/src/plugins
        depends_on:
            - db
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DEFAULT_DB_NAME=${DEFAULT_DB_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - API_DEBUG=${API_DEBUG}

    celery_worker:
        init: true
        build:
            context: ./
            dockerfile: ./configurations/api/Dockerfile
        restart: always
        volumes:
            - ./api:/usr/src/app
            - ./plugins:/usr/src/plugins
        depends_on:
            - db
            - redis
        command: /usr/local/bin/watchmedo auto-restart --directory=/usr/src/ --pattern=*.py --recursive -- /usr/local/bin/celery -A munity worker -l info
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DEFAULT_DB_NAME=${DEFAULT_DB_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - API_DEBUG=${API_DEBUG}

    celery_beat:
        build:
            context: ./
            dockerfile: ./configurations/api/Dockerfile
        restart: always
        volumes:
            - ./api:/usr/src/app
            - ./plugins:/usr/src/plugins
        depends_on:
            - db
            - redis
        entrypoint: /docker-entrypoint.d/10-runplugins.sh
        command: /usr/local/bin/celery -A munity beat -l INFO
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DEFAULT_DB_NAME=${DEFAULT_DB_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - API_DEBUG=${API_DEBUG}

    app:
        init: true
        build:
            context: ./
            dockerfile: ./configurations/app/Dockerfile
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.app.rule=HostRegexp(`${HOMEPAGE_URL}`, `{workspace:[a-z]+}.${APP_SUFFIX_URL}`)"
        volumes:
            - ./app:/var/www

    websocket:
        init: true
        build:
            context: ./
            dockerfile: ./configurations/websocket/Dockerfile
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.websocket.rule=HostRegexp(`{workspace:[a-z]+}.websocket.${APP_SUFFIX_URL}`)"
        volumes:
            - ./websocket:/home/node/app
        command: "yarn start"
        expose:
            - 80
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

    db:
        init: true
        image: timescale/timescaledb:2.2.0-pg11
        volumes:
            - volume-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - PGDATA=${PGDATA}

    redis:
        init: true
        image: redis:6.2.2
        volumes:
            - volume-redis:/data

volumes:
    volume-db:
        name: ${HOMEPAGE_URL}-volume-db
    volume-redis:
        name: ${HOMEPAGE_URL}-volume-redis
